# docker run --name underworld -e POSTGRESQL_USERNAME=master -e POSTGRESQL_PASSWORD=sakeador -e POSTGRESQL_DATABASE=gympass -p 5432:5432 bitnami/postgresql

version: '3'

services:
  underworld:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=master
      - POSTGRESQL_PASSWORD=sakeador
      - POSTGRESQL_DATABASE=gympass